SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- =========================================================================
-- TABLE CREATION (STACK SERVICE SCHEMA)
-- =========================================================================

CREATE TABLE public.menu_permission (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    menu_id bigint NOT NULL,
    permission_id bigint NOT NULL
);

CREATE TABLE public.menus (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    label character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    display_order integer NOT NULL
);

CREATE TABLE public.permissions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    label character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE public.portfolio_alert_thresholds (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    lower_alert_price numeric(19,4) NOT NULL,
    lower_threshold_percent numeric(5,2) NOT NULL,
    ticker_symbol character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    upper_alert_price numeric(19,4) NOT NULL,
    upper_threshold_percent numeric(5,2) NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE public.stacks (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    active boolean NOT NULL,
    company_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    ticker_symbol character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

CREATE TABLE public.stock_alert_history (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    alert_type character varying(255),
    buying_price numeric(38,2),
    created_at timestamp(6) without time zone,
    current_price numeric(38,2),
    email_sent boolean NOT NULL,
    gain_loss_per_stock numeric(38,2),
    ticker_symbol character varying(255),
    total_gain_loss numeric(38,2),
    user_id bigint
);

CREATE TABLE public.stocks (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    active boolean NOT NULL,
    company_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    exchange character varying(50) NOT NULL,
    ticker_symbol character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone
);

CREATE TABLE public.use_menu_permission (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    menu_permission_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE public.user_menu_permission (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    menu_permission_id bigint NOT NULL,
    user_id bigint NOT NULL
);

-- Safely reconstructed truncated snippet from original dump
CREATE TABLE public.user_portfolios (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    buying_price numeric(38,2) NOT NULL,
    company_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    ticker_symbol character varying(255) NOT NULL
);
