spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investor_db
    username: postgres
    password: jayaram@9959

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080
kind: Application

jwt:
  secret: "this-is-my-super-secure-jwt-secret-key-2026-for-investor-app"
  expiration-ms: 3600000